apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
spec:
  # This configuration is for Istio 1.30.4, the version used by this repository.
  profile: default
  components:
    pilot:
      enabled: true
      k8s:
        replicaCount: 2
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          replicaCount: 2
          service:
            type: LoadBalancer
          serviceAnnotations:
            load-balancer.hetzner.cloud/location: fsn1
            load-balancer.hetzner.cloud/type: lb11
            external-dns.kubernetes.io/hostname: final-work-k8s.raisa44.men
            load-balancer.hetzner.cloud/use-private-ip: true
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
    egressGateways:
      - name: istio-egressgateway
        enabled: false
