- name: gather facts from the control_plane
  tags: [ 'control_plane' ]
  setup:
  delegate_to: "{{item}}"
  delegate_facts: True
  with_items: "{{groups['control_plane']}}"

- name: install haproxy
  apt:
    name: haproxy
    state: present
    update_cache: true
    force: yes

- name: Stop haproxy service
  service:
    name: haproxy
    state: stopped

- name: Create "{{ haproxy_cfg }}"
  template:
    src: haproxy.j2
    dest: "{{ haproxy_cfg }}"
    owner: root
    group: root
    mode: "0644"

- name: start haproxy service
  service:
    name: haproxy
    state: started