apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubelet-csr-approver
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubelet-csr-approver
rules:
  - apiGroups: [certificates.k8s.io]
    resources: [certificatesigningrequests]
    verbs: [get, list, watch]
  - apiGroups: [certificates.k8s.io]
    resources: [certificatesigningrequests/approval]
    verbs: [update]
  - apiGroups: [certificates.k8s.io]
    resources: [signers]
    resourceNames: [kubernetes.io/kubelet-serving]
    verbs: [approve]
  - apiGroups: [coordination.k8s.io]
    resources: [leases]
    verbs: [create, get, update]
  - apiGroups: ['']
    resources: [events]
    verbs: [create]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubelet-csr-approver
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubelet-csr-approver
subjects:
  - kind: ServiceAccount
    name: kubelet-csr-approver
    namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubelet-csr-approver
  namespace: kube-system
  labels:
    app: kubelet-csr-approver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubelet-csr-approver
  template:
    metadata:
      labels:
        app: kubelet-csr-approver
    spec:
      serviceAccountName: kubelet-csr-approver
      nodeSelector:
        node-role.kubernetes.io/control-plane: ''
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    app: kubelet-csr-approver
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: kubelet-csr-approver
          image: ghcr.io/postfinance/kubelet-csr-approver:v1.2.14
          imagePullPolicy: IfNotPresent
          args:
            - -metrics-bind-address=:8080
            - -health-probe-bind-address=:8081
            - -leader-election
          env:
            - name: PROVIDER_REGEX
              value: '^((master|worker|ingress)-[0-9]+)$'
            - name: PROVIDER_IP_PREFIXES
              value: '192.168.0.0/16'
            - name: BYPASS_DNS_RESOLUTION
              value: 'true'
            - name: MAX_EXPIRATION_SEC
              value: '31536000'
          ports:
            - name: metrics
              containerPort: 8080
            - name: health
              containerPort: 8081
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /healthz
              port: health
