- hosts: all
  become: true
  gather_facts: true
  roles:
    - { role: preparing_hosts, tags: ['preparing_hosts'], when: enables_roles.preparing_hosts }
    - { role: cluster, tags: ['cluster'], when: enables_roles.cluster }
